/* eslint-disable prettier/prettier */
export default {
    // STACK SCREEN
    HOME_STACK: 'HOME_STACK',


    //AUTH SCREENS
    ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
    WELCOME_ROLE_SCREEN: 'WELCOME_ROLE_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    OTP_LOGIN_SCREEN: 'OTP_LOGIN_SCREEN',

    //APP SCREENS
    HOME_SCREEN: 'HOME_SCREEN',
    SOC_HOME_SCREEN: 'SOC_HOME_SCREEN',
    SEARCH_SCREEN: 'SEARCH_SCREEN',
    INQUIRY_SCREEN: 'INQUIRY_SCREEN',
    CUSTOMER_ACCOUNT_SCREEN: 'CUSTOMER_ACCOUNT_SCREEN',
    CUSTOMER_PROFILE_TAB: 'CUSTOMER_PROFILE_TAB',
    INVOICE_DETAILS: 'INVOICE_DETAILS',
    INVOICE_PREVIEW: 'INVOICE_PREVIEW',
    COLLECT_PAYMENT: 'COLLECT_PAYMENT',
    CLOSE_INQUIRY: 'CLOSE_INQUIRY',
    SERVICE_DETAIL: 'SERVICE_DETAIL',
    CHAT_SCREEN: 'CHAT_SCREEN',
    CONFIRM_SERVICES: 'CONFIRM_SERVICES',
    SERVICES_SCREEN: 'SERVICES_SCREEN',
    SERVICES_INFO: 'SERVICES_INFO',
    CONFIRM_SERVICE_INFO: 'CONFIRM_SERVICE_INFO',
    PAYMENT_DETAILS: 'PAYMENT_DETAILS',
    ITEM_DETAILS: 'ITEM_DETAILS',
    QR_CODE_SCREEN: 'QR_CODE_SCREEN',
    INVOICES_LIST: 'INVOICES_LIST',
    PICKUP_HANDOVER: 'PICKUP_HANDOVER',
    ASSESMENT_ITEMS: 'ASSESMENT_ITEMS',
    ITEM_ASSESMENT: 'ITEM_ASSESMENT',
};



