/* eslint-disable prettier/prettier */
export default {
    // STACK SCREEN
    HOME_STACK: 'HOME_STACK',


    //AUTH SCREENS
    ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
    WELCOME_ROLE_SCREEN: 'WELCOME_ROLE_SCREEN',
    LOGIN_SCREEN: 'LOGIN_SCREEN',
    OTP_LOGIN_SCREEN: 'OTP_LOGIN_SCREEN',

    //APP SCREENS
    HOME_SCREEN: 'HOME_SCREEN',
    SOC_HOME_SCREEN: 'SOC_HOME_SCREEN',
    SEARCH_SCREEN: 'SEARCH_SCREEN',
    INQUIRY_SCREEN: 'INQUIRY_SCREEN',
    CUSTOMER_ACCOUNT_SCREEN: 'CUSTOMER_ACCOUNT_SCREEN',
};



